# Generated by Django 4.2.11 on 2024-08-13 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('status', models.CharField(choices=[('PENDING', 'Waiting for Payment'), ('PAID', 'Successfully paid')], default='PENDING', max_length=24)),
                ('payment_type', models.CharField(choices=[('PAYMENT_FOR_BOOK', 'Payment for book'), ('FINE_FOR_DELAY', 'Fine for delay')], default='PAYMENT_FOR_BOOK', max_length=24)),
                ('session_url', models.URLField()),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('borrowing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='borrowing.borrowing')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
