# Generated by Django 5.1 on 2024-08-13 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=24)),
                ('payment_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], default='PAYMENT', max_length=24)),
                ('session_url', models.URLField()),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('borrowing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='borrowing.borrowing')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
