# Generated by Django 4.2.11 on 2024-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_type_alter_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
