# Generated by Django 5.1 on 2024-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
