# Generated by Django 5.1 on 2024-08-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        ('payment', '0002_alter_payment_payment_type_alter_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='payment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
            preserve_default=False,
        ),
    ]
